---
# ----------------------------------------------------
# SIGbOX backend config file
# ----------------------------------------------------

# Logging level 
# CRITICAL = 50, ERROR = 40, WARNING = 30, INFO = 20, DEBUG = 10, NOTSET = 0
logging_level: 10

# Pushbullet configuration
pushbullet:
    api: KcP0dywlqiu0dp1NrH6mI3IWAUOB3ZJt
